basePath: /api/v1/
definitions:
  controller.Result:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
  description: 给心阅博客网站前端提供API
  license: {}
  title: 心阅博客
  version: 0.0.1
paths:
  /Comment/:
    get:
      consumes:
      - application/json
      description: 用于获取某篇文章的评论
      parameters:
      - description: 文章id
        in: formData
        name: ArticleID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":nil,"msg": "查询评论成功！"}'
          schema:
            $ref: '#/definitions/controller.Result'
        "400":
          description: '{"code":400,"data":nil,"msg": "查询评论失败！"}'
          schema:
            $ref: '#/definitions/controller.Result'
      summary: 获取文章评论
      tags:
      - 评论模块
  /PublishArticle:
    post:
      consumes:
      - application/json
      description: 用于用户发布文章
      parameters:
      - description: 文章标题
        in: formData
        name: title
        required: true
        type: string
      - description: 文章内容
        in: formData
        name: content
        required: true
        type: string
      - description: 文章摘要
        in: formData
        name: summary
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":nil,"msg": "发布成功！"}'
          schema:
            $ref: '#/definitions/controller.Result'
        "400":
          description: '{"code":400,"data":nil,"msg": "后端获取文章失败！"}'
          schema:
            $ref: '#/definitions/controller.Result'
      summary: 发布一篇文章
      tags:
      - 文章模块
swagger: "2.0"
